import fs from 'node:fs/promises'
import path from 'node:path'
import { parseBiomeRules } from '../parsers/biome-parser.ts'
import { parseESLintRules } from '../parsers/eslint-parser.ts'
import type { BiomeRageResult } from '../tools/biome-runner.ts'
import type { ESLintConfigResult } from '../tools/eslint-runner.ts'
import { Logger } from '../utils/logger.ts'
import { lintRulesToMarkdown } from './lint-to-markdown.ts'

interface MarkdownGeneratorOptions {
  biomeResult: BiomeRageResult | null
  eslintResult: ESLintConfigResult | null
  outputFile: string
}

/**
 * Guess project name
 */
function guessProjectName(): string {
  try {
    // It's possible to implement getting the project name from package.json,
    // but for now it's fine to use a fixed name
    return 'Project'
  } catch {
    return 'Project'
  }
}

/**
 * Generate table of contents
 */
function generateTableOfContents(hasBiome: boolean, hasEslint: boolean): string {
  let toc = '## 📑 Table of Contents\n\n'

  toc += '- [Introduction](#introduction)\n'
  toc += '- [AI Usage Guide](#ai-usage-guide)\n'

  if (hasBiome) {
    toc += '- [Biome Rules](#biome-rules)\n'
    // It's possible to enumerate all categories, but keeping it simple
  }

  if (hasEslint) {
    toc += '- [ESLint Rules](#eslint-rules)\n'
    // It's possible to enumerate all categories, but keeping it simple
  }

  return toc
}

/**
 * Generate document header
 */
function generateHeader(): string {
  const projectName = guessProjectName()
  return `# ${projectName} Lint Rules Reference\n\n## 📋 Document Overview\n\nThis document contains a comprehensive catalog of linting rules enabled in this project. It is automatically generated by [Rulens](https://github.com/MH4GF/rulens) and provides AI code assistants and developers with detailed information about code style and quality requirements.\n\n`
}

/**
 * Generate introduction
 */
function generateIntroduction(): string {
  return (
    '## 📖 Introduction\n\n' +
    'This document lists all active linting rules configured in the project. Each rule includes:\n\n' +
    '- A link to official documentation\n' +
    '- A brief description of what the rule enforces\n' +
    '- Severity level (when available)\n\n' +
    'Use this reference to understand the code standards and avoid common issues when writing or reviewing code.\n\n'
  )
}

/**
 * Generate AI usage guide
 */
function generateAIUsageGuide(): string {
  return (
    '## 🤖 AI Usage Guide\n\n' +
    '**For AI Code Assistants**: When generating code for this project, please adhere to the following guidelines:\n\n' +
    `1. **Scan relevant categories first**: Focus on rules in categories related to the code you're generating.\n` +
    '2. **Respect all rules**: Ensure all generated code follows all linting rules.\n' +
    '3. **Avoid common pitfalls**: Check complexity rules to avoid anti-patterns.\n\n' +
    'When uncertain about specific rules, refer to the rule documentation links provided.\n\n'
  )
}

/**
 * Ensure directory exists before writing file
 */
async function ensureDirectoryExists(filePath: string): Promise<void> {
  const directory = path.dirname(filePath)
  try {
    await fs.mkdir(directory, { recursive: true })
  } catch (error) {
    // Ignore error if directory already exists
    if ((error as NodeJS.ErrnoException).code !== 'EEXIST') {
      throw error
    }
  }
}

export async function generateMarkdown(options: MarkdownGeneratorOptions): Promise<string> {
  const { biomeResult, eslintResult, outputFile } = options
  const logger = new Logger()

  logger.info(`Generating markdown for ${outputFile}...`)

  // Generate each part of the document
  let markdown = generateHeader()
  markdown += '---\n\n'

  // Add table of contents
  markdown += generateTableOfContents(!!biomeResult, !!eslintResult)
  markdown += '---\n\n'

  // Add introduction and AI usage guide
  markdown += generateIntroduction()
  markdown += '---\n\n'
  markdown += generateAIUsageGuide()
  markdown += '---\n\n'

  // 1. Convert Biome configuration to common intermediate representation
  if (biomeResult) {
    const biomeLinter = parseBiomeRules(biomeResult)
    markdown += `${lintRulesToMarkdown(biomeLinter, true)}\n`
  }

  // 2. Convert ESLint configuration to common intermediate representation
  if (eslintResult) {
    const eslintLinter = parseESLintRules(eslintResult)
    markdown += lintRulesToMarkdown(eslintLinter, true)
  }

  await ensureDirectoryExists(outputFile)

  // Write to file
  await fs.writeFile(outputFile, markdown, 'utf-8')

  return markdown
}
